Refining build
Refers to #5

diff --git a/.github/workflows/mainbuild.yml b/.github/workflows/mainbuild.yml
--- a/.github/workflows/mainbuild.yml
+++ b/.github/workflows/mainbuild.yml
@@ -6,6 +6,15 @@ on:
       - 'v*'
       - 'dev-*'
   workflow_dispatch:
+    inputs:
+      publish:
+        description: 'Publish to Visual Studio Marketplace?'
+        required: true
+        default: 'false'
+        type: choice
+        options:
+          - 'true'
+          - 'false'
 
 jobs:
   build:
@@ -44,3 +53,26 @@ jobs:
         with:
           name: bc-extension-dev
           path: 'bc-tools-extension/*.vsix'
+
+      - name: Publish to marketplace
+        if: ${{ github.event.inputs.publish == 'true' }}
+        run: |
+          if [ -z "$ADO_PAT" ]; then
+            echo "ADO_PAT not available; skipping publish"
+            exit 0
+          fi
+
+          if ! ls *.vsix 1> /dev/null 2>&1; then
+            echo "VSIX not found; skipping publish"
+            exit 0
+          fi
+
+          VSIX_FILE=$(ls *.vsix | head -n 1)
+
+          echo "Publishing using VSIX:"
+          echo "$VSIX_FILE"
+
+          tfx extension publish --vsix "$VSIX_FILE" --token $ADO_PAT
+        working-directory: bc-tools-extension
+        env:
+          ADO_PAT: ${{ secrets.ADO_PAT }}
